background #{{colors.background.default.hex_stripped}}
foreground #{{colors.on_background.default.hex_stripped}}
selection_background #{{colors.primary.default.hex_stripped}}
selection_foreground #{{colors.on_primary.default.hex_stripped}}
cursor #{{colors.primary.default.hex_stripped}}
url_color #{{colors.primary.default.hex_stripped}}
