#!/usr/bin/env bash
# Regenerates the "HyprlandRice" color scheme in the local Sleek theme copy
# from the current matugen accent, then re-applies spicetify. Run after
# set-theme-color.sh so Spotify's colors track the rest of the rice — Sleek
# is installed system-wide (spicetify-themes-git, /opt/spicetify-cli/Themes)
# but that's root-owned, so we keep an editable copy under
# ~/.config/spicetify/Themes/Sleek instead of patching it in place.
set -euo pipefail

SLEEK_DIR="${HOME}/.config/spicetify/Themes/Sleek"
COLORS_CONF="${HOME}/.config/hypr/colors.conf"

[[ -f "${COLORS_CONF}" ]] || { echo "No colors.conf yet, skipping spicetify sync" >&2; exit 0; }
[[ -d "${SLEEK_DIR}" ]] || { echo "Sleek theme not found at ${SLEEK_DIR} — install spicetify-themes-git" >&2; exit 0; }

hex_of() {
  # extracts rgb(xxxxxx) -> xxxxxx from a `$name = rgb(hex)` line
  grep -oP "^\\\$${1} = rgb\(\K[0-9a-fA-F]{6}" "${COLORS_CONF}"
}

accent="$(hex_of accent)"
on_accent="$(hex_of on_accent)"
background="$(hex_of background)"
surface="$(hex_of surface)"
surface_variant="$(hex_of surface_variant)"
on_background="$(hex_of on_background)"
error="$(hex_of error)"

# Strip any previous HyprlandRice section, then append a fresh one.
awk '/^\[HyprlandRice\]/{skip=1} /^\[/ && !/^\[HyprlandRice\]/{skip=0} !skip' \
  "${SLEEK_DIR}/color.ini" > "${SLEEK_DIR}/color.ini.tmp"
mv "${SLEEK_DIR}/color.ini.tmp" "${SLEEK_DIR}/color.ini"

cat >> "${SLEEK_DIR}/color.ini" <<EOF

[HyprlandRice]
; Generated by spicetify-sync-theme.sh from matugen's accent — do not hand-edit.
text               = ${accent}
subtext            = ${on_background}
nav-active-text    = ${on_accent}
main               = ${background}
sidebar            = ${background}
player             = ${background}
card               = ${surface}
shadow             = 000000
main-secondary     = ${surface_variant}
button             = ${accent}
button-secondary   = ${accent}
button-active      = ${accent}
button-disabled    = ${surface_variant}
nav-active         = ${accent}
play-button        = ${accent}
tab-active         = ${surface}
notification       = ${surface}
notification-error = ${error}
playback-bar       = ${accent}
misc               = ${on_accent}
EOF

spicetify config current_theme Sleek color_scheme HyprlandRice >/dev/null
spicetify update >/dev/null
